# Generated by Django 4.0 on 2022-01-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon1', models.IntegerField(max_length=4, null=True)),
                ('pokemon2', models.IntegerField(max_length=4, null=True)),
                ('pokemon3', models.IntegerField(max_length=4, null=True)),
                ('pokemon4', models.IntegerField(max_length=4, null=True)),
                ('pokemon5', models.IntegerField(max_length=4, null=True)),
                ('pokemon6', models.IntegerField(max_length=4, null=True)),
            ],
        ),
    ]
